version: 0.0
os: linux
files:
  - source: /
    destination: /var/task
permissions:
  - object: /
    pattern: "**/*"
    owner: root
    group: root
hooks:
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 300
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
